// components/pomodoro/sounds.ts
export interface Sound {
  id: number;
  title: string;
  description: string;
  url: string;
  thumbnail: string;
}

export const soundsList: Sound[] = [
  {
    id: 91,
    title:
      "سورة البقرة كاملة للشيخ د. ياسر الدوسري~طاردة الشياطين | Surat Al-Baqarah | Yasser Al-Dosari",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=P0uaLRO6V1U",
    thumbnail: "",
  },
  {
    id: 92,
    title:
      "تلاوة سورة الكهف كاملة بصوت الشيخ د. ياسر الدوسري Surah Al-Kahf",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=K8oByZjO8T4",
    thumbnail: "",
  },
  {
    id: 93,
    title:
      "Surah Al-Muminun | by sheikh yasser al dosari | سورة المؤمنون | الشیخ یاسر الدوسري",
    description: "AL HAMED | الحامد",
    url: "https://www.youtube.com/watch?v=_nx76MlMzFE",
    thumbnail: "",
  },
  {
    id: 94,
    title: "سورة المؤمنون - ياسر الدوسري - (كاملة)",
    description: "فهد العمري",
    url: "https://www.youtube.com/watch?v=Hu1PprY5lhU",
    thumbnail: "",
  },
  {
    id: 95,
    title:
      "روائع نادرة لا تتكرر من اجمل تلاوات الشيخ د.ياسر الدوسري لرمضان 1441هـ",
    description: "مزامير الفرقان - ياسر الدوسري",
    url: "https://www.youtube.com/watch?v=i11iRT_iF1I",
    thumbnail: "",
  },
  {
    id: 96,
    title:
      "‏يا لجمال هذه التلاوة! من سورتي القصص والعنكبوت للشيخ د. ياسر الدوسري | ليلة 23-9-1447هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=_6pTp5V_R3A",
    thumbnail: "",
  },
  {
    id: 97,
    title:
      "ما أعذبها! سورة الكهف كاملة للشيخ د. ياسر الدوسري | Surat Al-Kahf",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=GYqzkR_AnKE",
    thumbnail: "",
  },
  {
    id: 98,
    title:
      "أي جمال بعد هذا؟ سورة النور كاملة للشيخ ياسر الدوسري من ليالي رمضان عام 1442 هـ Surah An-Noor",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=A4HYgv21KXs",
    thumbnail: "",
  },
  {
    id: 99,
    title:
      "سورة مريم كاملة في تلاوة مبكية وخاشعة من الآسر د. ياسر الدوسري | ليالي رمضان 1441هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=WVMQC9E2j8A",
    thumbnail: "",
  },
  {
    id: 100,
    title:
      "سورة يسٓ كاملة للشيخ ياسر الدوسري من ليالي رمضان عام 1442 هـ Surah Yaseen",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=yEAmNisPOzk",
    thumbnail: "",
  },
  {
    id: 101,
    title:
      "من أجمل وأروع فجريات الغرّيد د. ياسر الدوسري | من 9 إلى 15 صفر 1447هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=2siX8fKSKr0",
    thumbnail: "",
  },
  {
    id: 102,
    title:
      "غرّيد الحرم د. ياسر الدوسري يُبحر بالمصلين من محراب الكعبة بتلاوة من سورة يونس | ليلة 15 رمضان 1447",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=_aOFof-FWkE",
    thumbnail: "",
  },
  {
    id: 103,
    title:
      "رقية المنزل الشيخ ياسر الدوسري سورة ( البقرة - يس - الرحمن - الواقعة - الملك) تلاوة عذبة",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=6ry-ldQ9CV4",
    thumbnail: "",
  },
  {
    id: 104,
    title:
      "سورة الرحمن للشيخ د. ياسر الدوسري - Surah Ar-Rahman | Yasser Al-Dosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=2BXD0oGxYYw",
    thumbnail: "",
  },
  {
    id: 105,
    title:
      "تلاوة تأخذ بتلابيب القلب لـ سورة الواقعة كاملة للآسر د. ياسر الدوسري | فجر 20-10-1443هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=PVeDA_1K8mc",
    thumbnail: "",
  },
  {
    id: 106,
    title:
      "من أجمل 5 تلاوات لفضيلة الشيخ ياسر الدوسري من الحرم المكي !😍",
    description: "مزامير الهُدى",
    url: "https://www.youtube.com/watch?v=TU5zDdtiNsk",
    thumbnail: "",
  },
  {
    id: 107,
    title: "سورة الإسراء - ياسر الدوسري (كاملة)",
    description: "فهد العمري",
    url: "https://www.youtube.com/watch?v=s8YZK9kpT9M",
    thumbnail: "",
  },
  {
    id: 108,
    title:
      "بخشوع وتجلى مع التحبير الرائع يفوق الوصف تلاوة للشيخ ياسر الدوسري",
    description: "Geza AlRoh",
    url: "https://www.youtube.com/watch?v=ShlFSSOh2aY",
    thumbnail: "",
  },
  {
    id: 109,
    title:
      "رقية المنزل الشيخ ياسر الدوسري سورة ( البقرة - يس - الرحمن - الواقعة - الملك) تلاوة عذبة",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=KJOZpGQjoac",
    thumbnail: "",
  },
  {
    id: 110,
    title: "سورة الشعراء - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=y2qX4NRXgAE",
    thumbnail: "",
  },
  {
    id: 111,
    title:
      "سورة طه بتحبير فريد للشيخ د. ياسر الدوسري من الحرم المكي | Surah Taha",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=kJ0L1E6dyrY",
    thumbnail: "",
  },
  {
    id: 112,
    title: "سورة القصص - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=bIjPgLkO7c0",
    thumbnail: "",
  },
  {
    id: 113,
    title: "سورة يوسف ياسر الدوسري",
    description: "قرآن كريم",
    url: "https://www.youtube.com/watch?v=VKqZNPG4o_4",
    thumbnail: "",
  },
  {
    id: 114,
    title:
      "سورة البقرة كاملة للشيخ د. ياسر الدوسري - Surat Al-Baqarah | Yasser Al-Dosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=vqQKIHfj0ao",
    thumbnail: "",
  },
  {
    id: 115,
    title:
      "سورة الكهف كاملة بصوت الشيخ د. ياسر الدوسري Surah Al-Kahf Sheikh Dr. Yasser Aldosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=51npIAQtCRU",
    thumbnail: "",
  },
  {
    id: 116,
    title: "سورة النمل - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=Y3o-caU1SKA",
    thumbnail: "",
  },
  {
    id: 117,
    title:
      "العِقدُ الآسِرْ لتلاوات الشيخ ياسر الدوسري | تلاوات شهر شوّال لعام 1447هـ من الحرم المكي",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=lFRWwNGAO_4",
    thumbnail: "",
  },
  {
    id: 118,
    title:
      "سورة المؤمنون بصوت ياسر الدوسري | تلاوة خاشعة تهز القلوب وتُحيي الإيمان 💛📖",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=kSnYpeKYJtk",
    thumbnail: "",
  },
  {
    id: 119,
    title:
      "سور الرزق ( يس - الرحمن - الواقعة - الملك) الشيخ ياسر الدوسري",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=CZS5Vf3K-pY",
    thumbnail: "",
  },
  {
    id: 120,
    title:
      "جميع تلاوات رمضان 1447هـ للغرّيد المبدع د. ياسر الدوسري ..",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=d4ZuUYWM4oA",
    thumbnail: "",
  },
    {
    id: 91,
    title: "سورة البقرة كاملة للشيخ د. ياسر الدوسري~طاردة الشياطين | Surat Al-Baqarah | Yasser Al-Dosari",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=P0uaLRO6V1U",
    thumbnail: "",
  },
  {
    id: 92,
    title: "تلاوة سورة الكهف كاملة بصوت الشيخ د. ياسر الدوسري Surah Al-Kahf",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=K8oByZjO8T4",
    thumbnail: "",
  },
  {
    id: 93,
    title: "Surah Al-Muminun | by sheikh yasser al dosari | سورة المؤمنون | الشیخ یاسر الدوسري",
    description: "AL HAMED | الحامد",
    url: "https://www.youtube.com/watch?v=_nx76MlMzFE",
    thumbnail: "",
  },
  {
    id: 94,
    title: "سورة المؤمنون - ياسر الدوسري - (كاملة)",
    description: "فهد العمري",
    url: "https://www.youtube.com/watch?v=Hu1PprY5lhU",
    thumbnail: "",
  },
  {
    id: 95,
    title: "روائع نادرة لا تتكرر من اجمل تلاوات الشيخ د.ياسر الدوسري لرمضان 1441هـ",
    description: "مزامير الفرقان - ياسر الدوسري",
    url: "https://www.youtube.com/watch?v=i11iRT_iF1I",
    thumbnail: "",
  },
  {
    id: 96,
    title: "‏يا لجمال هذه التلاوة! من سورتي القصص والعنكبوت للشيخ د. ياسر الدوسري | ليلة 23-9-1447هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=_6pTp5V_R3A",
    thumbnail: "",
  },
  {
    id: 97,
    title: "ما أعذبها! سورة الكهف كاملة للشيخ د. ياسر الدوسري | Surat Al-Kahf",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=GYqzkR_AnKE",
    thumbnail: "",
  },
  {
    id: 98,
    title: "أي جمال بعد هذا؟ سورة النور كاملة للشيخ ياسر الدوسري من ليالي رمضان عام 1442 هـ Surah An-Noor",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=A4HYgv21KXs",
    thumbnail: "",
  },
  {
    id: 99,
    title: "سورة مريم كاملة في تلاوة مبكية وخاشعة من الآسر د. ياسر الدوسري | ليالي رمضان 1441هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=WVMQC9E2j8A",
    thumbnail: "",
  },
  {
    id: 100,
    title: "سورة يسٓ كاملة للشيخ ياسر الدوسري من ليالي رمضان عام 1442 هـ Surah Yaseen",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=yEAmNisPOzk",
    thumbnail: "",
  },
  {
    id: 101,
    title: "من أجمل وأروع فجريات الغرّيد د. ياسر الدوسري | من 9 إلى 15 صفر 1447هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=2siX8fKSKr0",
    thumbnail: "",
  },
  {
    id: 102,
    title: "غرّيد الحرم د. ياسر الدوسري يُبحر بالمصلين من محراب الكعبة بتلاوة من سورة يونس | ليلة 15 رمضان 1447",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=_aOFof-FWkE",
    thumbnail: "",
  },
  {
    id: 103,
    title: "رقية المنزل الشيخ ياسر الدوسري سورة ( البقرة - يس - الرحمن - الواقعة - الملك) تلاوة عذبة",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=6ry-ldQ9CV4",
    thumbnail: "",
  },
  {
    id: 104,
    title: "سورة الرحمن للشيخ د. ياسر الدوسري - Surah Ar-Rahman | Yasser Al-Dosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=2BXD0oGxYYw",
    thumbnail: "",
  },
  {
    id: 105,
    title: "تلاوة تأخذ بتلابيب القلب لـ سورة الواقعة كاملة للآسر د. ياسر الدوسري | فجر 20-10-1443هـ",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=PVeDA_1K8mc",
    thumbnail: "",
  },
  {
    id: 106,
    title: "من أجمل 5 تلاوات لفضيلة الشيخ ياسر الدوسري من الحرم المكي !😍",
    description: "مزامير الهُدى",
    url: "https://www.youtube.com/watch?v=TU5zDdtiNsk",
    thumbnail: "",
  },
  {
    id: 107,
    title: "سورة الإسراء - ياسر الدوسري (كاملة)",
    description: "فهد العمري",
    url: "https://www.youtube.com/watch?v=s8YZK9kpT9M",
    thumbnail: "",
  },
  {
    id: 108,
    title: "بخشوع وتجلى مع التحبير الرائع يفوق الوصف تلاوة للشيخ ياسر الدوسري",
    description: "Geza AlRoh",
    url: "https://www.youtube.com/watch?v=ShlFSSOh2aY",
    thumbnail: "",
  },
  {
    id: 109,
    title: "رقية المنزل الشيخ ياسر الدوسري سورة ( البقرة - يس - الرحمن - الواقعة - الملك) تلاوة عذبة",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=KJOZpGQjoac",
    thumbnail: "",
  },
  {
    id: 110,
    title: "سورة الشعراء - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=y2qX4NRXgAE",
    thumbnail: "",
  },
  {
    id: 111,
    title: "سورة طه بتحبير فريد للشيخ د. ياسر الدوسري من الحرم المكي | Surah Taha",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=kJ0L1E6dyrY",
    thumbnail: "",
  },
  {
    id: 112,
    title: "سورة القصص - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=bIjPgLkO7c0",
    thumbnail: "",
  },
  {
    id: 113,
    title: "سورة يوسف ياسر الدوسري",
    description: "قرآن كريم",
    url: "https://www.youtube.com/watch?v=VKqZNPG4o_4",
    thumbnail: "",
  },
  {
    id: 114,
    title: "سورة البقرة كاملة للشيخ د. ياسر الدوسري - Surat Al-Baqarah | Yasser Al-Dosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=vqQKIHfj0ao",
    thumbnail: "",
  },
  {
    id: 115,
    title: "سورة الكهف كاملة بصوت الشيخ د. ياسر الدوسري Surah Al-Kahf Sheikh Dr. Yasser Aldosari",
    description: "أ.د ياسر بن راشد الدوسري",
    url: "https://www.youtube.com/watch?v=51npIAQtCRU",
    thumbnail: "",
  },
  {
    id: 116,
    title: "سورة النمل - الشيخ ياسر الدوسري - 1425 هـ",
    description: "ءَادَم",
    url: "https://www.youtube.com/watch?v=Y3o-caU1SKA",
    thumbnail: "",
  },
  {
    id: 117,
    title: "العِقدُ الآسِرْ لتلاوات الشيخ ياسر الدوسري | تلاوات شهر شوّال لعام 1447هـ من الحرم المكي",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=lFRWwNGAO_4",
    thumbnail: "",
  },
  {
    id: 118,
    title: "سورة المؤمنون بصوت ياسر الدوسري | تلاوة خاشعة تهز القلوب وتُحيي الإيمان 💛📖",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=kSnYpeKYJtk",
    thumbnail: "",
  },
  {
    id: 119,
    title: "سور الرزق ( يس - الرحمن - الواقعة - الملك) الشيخ ياسر الدوسري",
    description: "القناة الرسمية للشيخ ياسر الدوسري بث مباشر",
    url: "https://www.youtube.com/watch?v=CZS5Vf3K-pY",
    thumbnail: "",
  },
  {
    id: 120,
    title: "جميع تلاوات رمضان 1447هـ للغرّيد المبدع د. ياسر الدوسري ..",
    description: "تلاوات ياسر الدوسري إمام الحرم المكي",
    url: "https://www.youtube.com/watch?v=d4ZuUYWM4oA",
    thumbnail: "",
  },
  {
    id: 121,
    title: "ترتيل بياتي لم ولن ينسى لسورتي الصافات و ص للشيخ ناصر القطامي من رمضان 1440هـ",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=Zhh43vT-2Ho",
    thumbnail: "",
  },
  {
    id: 122,
    title: "سورة يوسف | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-Yusuf",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=6xwC6Vpz47U",
    thumbnail: "",
  },
  {
    id: 123,
    title: "أداء مهيب وتلاوة خاشعة فضيلة الشيخ ناصر القطامي Beautiful Quran Recitation",
    description: "قران كريم - holyquran",
    url: "https://www.youtube.com/watch?v=7FyCCViqTq4",
    thumbnail: "",
  },
  {
    id: 124,
    title: "تلاوه هادئـه لتستريح  |  ناصـر القطامـى",
    description: "تلاوات هـادئـة",
    url: "https://www.youtube.com/watch?v=Fck_lDnYJRo",
    thumbnail: "",
  },
  {
    id: 125,
    title: "سورة البقرة | المصحف المرئي المرتل للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-AlBaqarah",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=Wg9x4yTI6XM",
    thumbnail: "",
  },
  {
    id: 126,
    title: "من أروع وأجمل فجريات الشيخ ناصر القطامي في عام 1445هـ",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=2QMDaMHSpHE",
    thumbnail: "",
  },
  {
    id: 127,
    title: "سورة مريم | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-Maryam",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=U2AV2TqJmfQ",
    thumbnail: "",
  },
  {
    id: 128,
    title: "تلاوة جميلة ورائعة من سورة سبأ للشيخ ناصر القطامي | ٢٨-٢-١٤٤٠هـ",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=ytDBZW-1K50",
    thumbnail: "",
  },
  {
    id: 129,
    title: "سورة الكهف | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-AlKahf",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=7Cw4Iq1_ork",
    thumbnail: "",
  },
  {
    id: 130,
    title: "سورة الواقعة | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-AlWaqi'ah",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=f3rQGSWWh_8",
    thumbnail: "",
  },
  {
    id: 131,
    title: "روائع تاريخية لم و لن تُنسى من أجمل الرمضانات للشيخ ناصر القطامي | رمضان 1436هـ",
    description: "مزامير الفرقان - ياسر الدوسري",
    url: "https://www.youtube.com/watch?v=uGV7LXTYp8E",
    thumbnail: "",
  },
  {
    id: 132,
    title: "سورة هود | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-Hud",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=RbTocMHYh3s",
    thumbnail: "",
  },
  {
    id: 133,
    title: "The most beautiful recitation by Sheikh Nasser Al-Qatami, a source of peace of mind.",
    description: "قناة شَهِيد ٱلۡمِحۡرَابَ (عليه السلام)",
    url: "https://www.youtube.com/watch?v=ufCGbSMYgNs",
    thumbnail: "",
  },
  {
    id: 134,
    title: "الشيخ ناصر القطامي -  سورة الواقعة ابكت المصلين  | تهجد ليلة ٢٧ رمضان ١٤٣٨هـ",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=_8ylWl9zUiY",
    thumbnail: "",
  },
  {
    id: 135,
    title: "عندما يجتمع الإتقان مع الخشوع… تسمع هذا | الشيخ ناصر القطامي... جودة نقية ᴴᴰ",
    description: "قران كريم - holyquran",
    url: "https://www.youtube.com/watch?v=qFrljPKWM6c",
    thumbnail: "",
  },
  {
    id: 136,
    title: "سورة طه | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-TaHa",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=-WEpqByP_PQ",
    thumbnail: "",
  },
  {
    id: 137,
    title: "تلاوة لا توصف تخترق القلوب 💖 والعقول للشيخ ناصر القطامي لما تيسر من سورتي النساء والمائده .صوت نقي.🎧",
    description: "قران كريم - holyquran",
    url: "https://www.youtube.com/watch?v=jKoeVzfuZXs",
    thumbnail: "",
  },
  {
    id: 138,
    title: "فجرية رائع للشيخ ناصر القطامي | 21-10-1440",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=Ea4zfaeIPgc",
    thumbnail: "",
  },
  {
    id: 139,
    title: "سورة النور | المصحف المرئي للشيخ ناصر القطامي من رمضان ١٤٣٨هـ | Surah-AnNur",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=7WYWne2Lz3U",
    thumbnail: "",
  },
  {
    id: 140,
    title: "فجرية هادئة من عالم أخر | ناصر القطامي",
    description: "Quranic Solace",
    url: "https://www.youtube.com/watch?v=gXBpad9Uuo8",
    thumbnail: "",
  },
  {
    id: 141,
    title: "المصحف المرتل كاملًا بصوت الشيخ ناصر القطامي من رمضان 1444هـ .",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=_uVYDpin8fs",
    thumbnail: "",
  },
  {
    id: 142,
    title: "الصافات ص الزمر غافر | ليلة تاريخية لا تنسى للشيخ ناصر القطامي - تراويح وتهجد ليلة 25 رمضان 1440هـ",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=vq-mNCco954",
    thumbnail: "",
  },
  {
    id: 143,
    title: "سورة طه بصوت هادئ وخشوع رائع للشيخ ناصر القطامي",
    description: "بيّـنات",
    url: "https://www.youtube.com/watch?v=kOHF7IWJfko",
    thumbnail: "",
  },
  {
    id: 144,
    title: "من اروع وأجمل ماترنم به الشيخ ناصر القطامي | فجرية الثلاثاء 27-2-1445",
    description: "تدابير القرآن",
    url: "https://www.youtube.com/watch?v=iee-EZoQBU0",
    thumbnail: "",
  },
  {
    id: 145,
    title: "من أروع وأجمل فجريات الشيخ ناصر القطامي في عام 1445هـ 1",
    description: "قناة سلطان  التعليمية",
    url: "https://www.youtube.com/watch?v=20_CJQYnegc",
    thumbnail: "",
  },
  {
    id: 146,
    title: "من أجمل التلاوات للشيخ ناصر القطامي بترتيل نادر  | رمضان 1440هـ",
    description: "تلاوات روحانية",
    url: "https://www.youtube.com/watch?v=vH0yIJlEKMI",
    thumbnail: "",
  },
  {
    id: 147,
    title: "فجرية هادئة للشيخ ناصر القطامي | 18-10-1440",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=2Bxt6zdGoNY",
    thumbnail: "",
  },
  {
    id: 148,
    title: "سورة البقرة كاملة  | ناصر القطامي",
    description: "القناة الرسمية للشيخ ناصر القطامي",
    url: "https://www.youtube.com/watch?v=2eZIcCNSLJw",
    thumbnail: "",
  },
  {
    id: 149,
    title: "سورة البقرة كاملة بصوت القارئ ناصر القطامي",
    description: "قران | Quran",
    url: "https://www.youtube.com/watch?v=UyuRKY6Cjgs",
    thumbnail: "",
  },
  {
    id: 150,
    title: "(أَفَمَنْ كَانَ مُؤْمِنًا كَمَنْ كَانَ فَاسِقًا) خااشعه للشيخ ناصر القطامي",
    description: "مزامير الفرقان - ياسر الدوسري",
    url: "https://www.youtube.com/watch?v=lxosSxYvGog",
    thumbnail: "",
  },
    {
    id: 151,
    title: "سورة التوبة تلاوة خاشعة ❤️ / القارئ محمد اللحيدان",
    description: "إحسان",
    url: "https://www.youtube.com/watch?v=9zu7dpztLFk",
    thumbnail: "",
  },
  {
    id: 152,
    title: "ما تيسَّر من سُورة الفُرقَان للقارئ محمد اللحيدان",
    description: "للقَارئ محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=-3CsAqSKkPs",
    thumbnail: "",
  },
  {
    id: 153,
    title: "{شاهد كيف قرأ محمد اللحيدان سورة المؤمنون} ؟ Surat Al-Mu'minun - Muhammad Al-Luhaidan",
    description: "قناة الريان youtube",
    url: "https://www.youtube.com/watch?v=I6hIWAYwx-M",
    thumbnail: "",
  },
  {
    id: 154,
    title: "الشيخ محمد اللحيدان يذهل السامعين بهذا الترتيل الجميل من سورة الفرقان من رمضان 1439",
    description: "نوادر التلاوات",
    url: "https://www.youtube.com/watch?v=BG8_Uycmh0A",
    thumbnail: "",
  },
  {
    id: 155,
    title: "(الله نور السماوات والأرض) تلاوة روحانية للشيخ محمد اللحيدان",
    description: "تلاوات د. محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=W5fh3ZLcpAE",
    thumbnail: "",
  },
  {
    id: 156,
    title: "{ عَيۡنٗا فِيهَا تُسَمَّىٰ سَلۡسَبِيلٗا } التلاوة الشهيرة لسورة الإنسان الشيخ محمد اللحيدان",
    description: "ابو عبدالعزيز | ١٤٣١هـ",
    url: "https://www.youtube.com/watch?v=eAeaFZQvN2o",
    thumbnail: "",
  },
  {
    id: 157,
    title: "تلاوة تُبكي القلوب بصوت قارئ القلوب محمد اللحيدان",
    description: "وِثَاق || 𝐖𝐓𝐀𝐐",
    url: "https://www.youtube.com/watch?v=W4Xz1sy1eZw",
    thumbnail: "",
  },
  {
    id: 158,
    title: "سورتي ( الرحمن والواقعة ) إستمع كيف تلاها الشيخ محمد اللحيدان بهذا الخشوع ليلة 28 - 1442",
    description: "تلاوات د. محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=XTUU0q8ndHA",
    thumbnail: "",
  },
  {
    id: 159,
    title: "سورة الإنسان كاملة بصوت محمد اللحيدان التلاوة المشهورة || كروما قران كريم شاشة سوداء",
    description: "كروما قرآن",
    url: "https://www.youtube.com/watch?v=PAEPg0bSA_k",
    thumbnail: "",
  },
  {
    id: 160,
    title: "شاهد كيف قرأ محمد اللحيدان سورة المؤمنون ✦ Surat Al Mu'minun Muhammad Al Luhaidan",
    description: "القرآن حياة القلوب",
    url: "https://www.youtube.com/watch?v=oa7nxI0xqoU",
    thumbnail: "",
  },
  {
    id: 161,
    title: "30 دقيقة من التلاوات الخاشعة بصوت القارئ الشيخ محمد اللحيدان💚",
    description: "𝐇𝐚𝐥𝐚𝐥 𝐀𝐈",
    url: "https://www.youtube.com/watch?v=dhOth0jpEww",
    thumbnail: "",
  },
  {
    id: 162,
    title: "[ يُضَاعَفْ لَهُ الْعَذَابُ ] عشائية تفوق الوصف للشيخ محمد اللحيدان في الخبر",
    description: "تلاوات روحانية",
    url: "https://www.youtube.com/watch?v=SEK_1BROTqQ",
    thumbnail: "",
  },
  {
    id: 163,
    title: "سورة مريم كاملة من أروع التلاوات للشيخ محمد اللحيدان جامع الرشدية دبي رمضان1440هـ",
    description: "روائع التلاوات",
    url: "https://www.youtube.com/watch?v=CUUWpyTfip8",
    thumbnail: "",
  },
  {
    id: 164,
    title: "سورة المعارج للشيخ محمد اللحيدان من أجمل العشائيات صفر 1443",
    description: "تلاوات د. محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=BKaQ7_6QM24",
    thumbnail: "",
  },
  {
    id: 165,
    title: "سورة الحاقة كاملة بصوت محمد اللحيدان التلاوة المشهورة || كروما قران كريم شاشة سوداء",
    description: "كروما قرآن",
    url: "https://www.youtube.com/watch?v=qhvWyrK3QfU",
    thumbnail: "",
  },
  {
    id: 166,
    title: "إنه هو البر الرحيم - أم خلقوا من غير شيء أم هم الخالقون - سورة الطور ١٤٣٤ 1434 محمد اللحيدان",
    description: "Luhidan Yasser",
    url: "https://www.youtube.com/watch?v=RQXHj_3822c",
    thumbnail: "",
  },
  {
    id: 167,
    title: "{ وجاءت سكرة الموت } إستمع كيف تلاها الشيخ محمد اللحيدان بالنبرة المؤثرة جدا",
    description: "تلاوات د. محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=YBr3ff5YCQk",
    thumbnail: "",
  },
  {
    id: 168,
    title: "سورة الأحزاب | تلاوة عميقة مؤثرة – محمد اللحيدان (Mohammed Al-Luhaidan)",
    description: "إحسان",
    url: "https://www.youtube.com/watch?v=jtVHX3XlUJQ",
    thumbnail: "",
  },
  {
    id: 169,
    title: "افضل تلاوات محمد اللحيدان (خشوع وراحه)",
    description: "Rashed alrashed",
    url: "https://www.youtube.com/watch?v=_OYt6l7lzJI",
    thumbnail: "",
  },
  {
    id: 170,
    title: "سورة البقره بصوت القارئ الشيخ محمد اللحيدان",
    description: "Quran_kromat",
    url: "https://www.youtube.com/watch?v=OngkgGnpyN8",
    thumbnail: "",
  },
  {
    id: 171,
    title: "تلاوة تبكي القلب قبل العين | سورة الزخرف | محمد اللحيدان",
    description: "أثر | Trace",
    url: "https://www.youtube.com/watch?v=68maP7xmj-w",
    thumbnail: "",
  },
  {
    id: 172,
    title: "سورة يوسف | أجمل قصة قرآنية بصوت خاشع – محمد اللحيدان (Mohammed Al-Luhaidan)",
    description: "إحسان",
    url: "https://www.youtube.com/watch?v=eM3JIheuD0E",
    thumbnail: "",
  },
  {
    id: 173,
    title: "والله يريد أن يتوب عليكم ويريد الذين.../محمد اللحيدان /سورة النساء",
    description: "قرآن_Quran",
    url: "https://www.youtube.com/watch?v=tu9h7cUiOdg",
    thumbnail: "",
  },
  {
    id: 174,
    title: "سورة الفرقان بترتيل خاشع من رمضان 1445 للشيخ محمد اللحيدان",
    description: "القرآن حياة القلوب",
    url: "https://www.youtube.com/watch?v=pHgRY_sEm2Q",
    thumbnail: "",
  },
  {
    id: 175,
    title: "Surah Al-Furqan [61-77] Muhammad Al Luhaidan | ‎سورة الفرقان محمد اللحيدان وكان الله غفورا رحيما",
    description: "glad with quran",
    url: "https://www.youtube.com/watch?v=Mg9gkMrgqro",
    thumbnail: "",
  },
  {
    id: 176,
    title: "سورة الطور كاملة || تلاوة تخطف الأنفاس وتبعث في القلب الراحة والسكينة🌷 || القارئ محمد اللحيدان🤍",
    description: "حناجر القراء",
    url: "https://www.youtube.com/watch?v=9dysDMx9yR0",
    thumbnail: "",
  },
  {
    id: 177,
    title: "الشيخ محمد اللحيدان | Muhammad Al-luhaidan سورة الكهف | Surat Al-kahf",
    description: "عبيدة الكردي",
    url: "https://www.youtube.com/watch?v=DxrxK2v2AHo",
    thumbnail: "",
  },
  {
    id: 178,
    title: "من أجمل تلاوات محمد اللحيدان | سورة الأنفال",
    description: "أثر | Trace",
    url: "https://www.youtube.com/watch?v=PO_9JNdKrUo",
    thumbnail: "",
  },
  {
    id: 179,
    title: "تلاوة تخليك تبكي بدون ما تحس | سورة المؤمنون | محمد اللحيدان",
    description: "أثر | Trace",
    url: "https://www.youtube.com/watch?v=Sb5QAuz7_lI",
    thumbnail: "",
  },
  {
    id: 180,
    title: "سورة الواقعة للشيخ محمد اللحيدان رمضان 1440هـ",
    description: "تلاوات د. محمد اللحيدان",
    url: "https://www.youtube.com/watch?v=cyolprUT4u8",
    thumbnail: "",
  },
];